name: black_dog
description: A Flutter project for black dog coffe.

version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  http:
  shared_preferences:
  barcode_scan:
  connectivity:
  modal_progress_hud:
  http_interceptor:
  flutter_sfsymbols:
  path_provider:
  carousel_slider:
  intl:
  url_launcher:
  flutter_svg:
  firebase_crashlytics:
  dotted_border:
  firebase_messaging:
  step_progress_indicator:
  firebase_auth:
  firebase_core:

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/

  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf

    - family: Century-Gothic
      fonts:
        - asset: assets/fonts/century_gothic.ttf

    - family: Lemon-Milk
      fonts:
        - asset: assets/fonts/lemon_milk.ttf

