name: black_dog
description: A Flutter project for black dog coffe.

version: 1.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  shared_preferences: ^0.5.12
  barcode_scan: ^3.0.1
  connectivity: ^0.4.9+3
  modal_progress_hud: ^0.1.3
  http_interceptor: ^0.3.2
  flutter_sfsymbols: ^1.0.0
  path_provider: ^1.6.18
  carousel_slider: ^2.2.1
  intl: ^0.16.1
  url_launcher: ^5.5.0
  flutter_svg: ^0.19.0
  firebase_crashlytics: ^0.1.4+1
  dotted_border: ^1.0.6
  firebase_messaging: ^7.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flutter_easyloading: ^1.2.1
  google_maps_flutter: ^0.5.33
  step_progress_indicator: ^0.2.4+7
  map_launcher: ^0.12.2

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/

  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf

    - family: Century-Gothic
      fonts:
        - asset: assets/fonts/century_gothic.ttf

    - family: Lemon-Milk
      fonts:
        - asset: assets/fonts/lemon_milk.ttf

